{{$serviceAccount := default dict .Values.serviceAccount}}
{{- if $serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "template.serviceAccountName" . }}
  labels:
{{ include "template.labels" . | nindent 4 }}
{{- end -}}
