{{$ingress:= default dict .Values.ingress}}
{{- if and $ingress.enabled $ingress.grpc -}}
{{- $fullName := include "template.serviceName" . -}}
{{- $paths := .Values.ingress.paths -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-grpc
  labels:
    {{- include "template.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if $ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- if (default "siop-teste.app.sof.intra" $ingress.host) }}
    - host: {{- if .Values.global }} {{  .Values.global.ingress.host }}  {{- else }} {{ default "siop-teste.app.sof.intra" .Values.ingress.host }}  {{- end }}
      http:
        paths:
        {{- range $p := $paths }}
          {{- if eq  (default "http" $p.protocol) "grpc" }}
          - path: {{ $p.path | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port: 
                  number: {{ $p.servicePort }}
          {{- end }}
        {{- end }}
  {{- end }}
{{- end }}
