{{$ingress:= default dict .Values.ingress}}
{{- $paths := .Values.ingress.paths -}}
{{- $fullName := include "template.serviceName" . -}}
{{- $namespace := .Release.Namespace -}}
{{- $build := include "template.build" . -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "template.serviceName" . }}
  labels:
    kiali_wizard: request_routing
spec:
  hosts:
    {{- if $ingress.enabled }}
    - {{- if .Values.global }} {{  .Values.global.ingress.host }}  {{- else }} {{ default "siop-teste.app.sof.intra" .Values.ingress.host }}  {{- end }}
    {{- else }}
    - {{ $fullName }}.{{ $namespace }}.svc.cluster.local
    {{- end}}
    {{- if $ingress.enabled }}
  gateways:
    - siop-ingressgateway
    {{- end }}
  http:
    {{- range .Values.ingress.paths }}
    - route:
        - destination:
            host: "{{ $fullName }}.{{ $namespace }}.svc.cluster.local"
            port:
              number: {{ .servicePort }}
            subset: v{{ $build }}
          weight: 100
      {{- if $ingress.enabled }}
      match:
        - uri:
            prefix: {{ .path | quote}}
      {{- end}}
        {{- end }}
